# This file will be generated by the installer if encryption is enabled
# Do not edit - it will be overwritten during installation
{ lib, ... }: {
  # Placeholder: will be replaced with actual encryption config
}
